### ISSUE TITLE
result on real scenario video

### ISSUE THREAD

**Issue by dragen1860** [ChrisAllenMing/Cross_Category_Video_Highlight#1]
Dear author:
   Thanks for the DA on VHD work.  I wonder have you tested the predicted HL curves on real scenario video, such as the videos captured by mobile phone on daily scene. Does it work also good and reasonable? thank you for giving some feedback about this.

**Comment by ChrisAllenMing** [comment]
Yeah, we have tested the model trained on the **sport** category of ActivityNet in real-world videos. Specifically, we feed several live videos from TikTok to our model, and the predicted top 5 highlight and non-highlight segments look reasonable. We are afraid not be able to provide this model because of some commercial use, but you can train such a model following the guidance of this repo.
